name: Auto Commit Daily

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update file
        run: |
          echo "Update: $(date)" >> activity.txt

      - name: Commit and push
        run: |
          git config --global user.name "frrdnnd"
          git config --global user.email "ferneedevweb@gmail.com"
          git add activity.txt
          git commit -m "auto update" || echo "no change"
          git push origin main --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}